# Generated by Django 4.2 on 2023-10-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='status',
            field=models.CharField(choices=[('1', 'ACTIVE'), ('2', 'NOT ACTIVE')], default='1', max_length=1),
        ),
    ]
