# Generated by Django 4.2 on 2023-10-03 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientaddress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='address2',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='address3',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
