# Generated by Django 4.2 on 2023-10-05 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_clientaddress_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactureraddress',
            name='address2',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufactureraddress',
            name='address3',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
