# Generated by Django 4.2 on 2024-03-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clientaddress_state_manufactureraddress_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manufactureraddress',
            name='country',
        ),
    ]
