# Generated by Django 4.2 on 2024-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_clientaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
