# Generated by Django 4.2 on 2023-09-25 08:59

import certificate.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_title', models.CharField(max_length=255)),
                ('standard_code', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Standards',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=30)),
                ('date_original_issue', models.DateField()),
                ('date_renewal', models.DateField()),
                ('date_amendment', models.DateField()),
                ('expiry_date', models.DateField(default=certificate.models.one_year_hence)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('country', django_countries.fields.CountryField(default='MY', max_length=2)),
                ('status', models.CharField(choices=[('1', 'DRAFT'), ('2', 'PUBLISHED'), ('3', 'EXPIRED')], default='1', max_length=1)),
                ('brands', models.ManyToManyField(blank=True, null=True, to='certificate.brand')),
            ],
        ),
    ]
