# Generated by Django 4.2 on 2023-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_rename_standard_title_standards_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standards',
            name='remark',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
