# Generated by Django 4.2 on 2023-10-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_certificate_annex'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
