# Generated by Django 4.2 on 2023-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_product_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='additional_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
