# Generated by Django 4.2 on 2023-11-28 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_remove_certificate_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.product'),
        ),
    ]
