# Generated by Django 4.2 on 2023-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0010_certificate_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='product',
        ),
        migrations.AddField(
            model_name='certificate',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='certificate.product'),
        ),
    ]
