# Generated by Django 4.2 on 2023-12-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0011_remove_certificate_product_certificate_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='additional_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
