# Generated by Django 4.2 on 2023-12-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0012_certificate_additional_information_certificate_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='material',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='model',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='size',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='type',
        ),
    ]
