# Generated by Django 4.2 on 2023-12-15 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0014_remove_certificate_product_certificate_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='brands',
        ),
        migrations.AddField(
            model_name='certificate',
            name='brands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.brand'),
        ),
    ]
