# Generated by Django 4.2 on 2023-12-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0015_remove_certificate_brands_certificate_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='product',
        ),
    ]
