# Generated by Django 4.2 on 2023-12-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0016_remove_certificate_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.certificate'),
        ),
    ]
