# Generated by Django 4.2 on 2023-12-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0018_product_additional_info_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='QRCode'),
        ),
    ]
