# Generated by Django 4.2 on 2023-12-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0020_alter_certificate_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='brands',
        ),
        migrations.AddField(
            model_name='certificate',
            name='brands',
            field=models.ManyToManyField(blank=True, to='certificate.brand'),
        ),
    ]
