# Generated by Django 4.2 on 2023-12-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0021_remove_certificate_brands_certificate_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='product_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
