# Generated by Django 4.2 on 2023-12-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0022_remove_product_product_name_certificate_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='annex',
        ),
    ]
