# Generated by Django 4.2 on 2023-12-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0023_remove_certificate_annex'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.CharField(choices=[('1', 'TEMPLATE 1'), ('2', 'TEMPLATE 2'), ('3', 'TEMPLATE 3')], default='1', max_length=1),
        ),
    ]
