# Generated by Django 4.2 on 2024-01-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0025_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
