# Generated by Django 4.2 on 2024-03-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0027_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='plant_identity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rmc_producer_code',
            field=models.TextField(blank=True, null=True, verbose_name="Ready-Mixed Concrete Producer's Code"),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
